### ISSUE TITLE
Display option is not available in the Permerhati Rang Undang-Undang page.

### ISSUE THREAD

**Issue by ghost** [Sinar/sinar.website#1]
I found that there is no "Display" option appeared on the menu bar for Permerhati Rang Undang-Undang.
![screen shot 2015-05-06 at 5 14 47 pm](https://cloud.githubusercontent.com/assets/11497391/7490518/c03fa652-f413-11e4-86d5-303055069b74.png)

Unlike menu bar for Wakil Rakyat and Kebebasan Maklumat which the "Display" option appeared just fine.
![screen shot 2015-05-06 at 5 18 07 pm](https://cloud.githubusercontent.com/assets/11497391/7490541/f4df7c7a-f413-11e4-9009-e25f011a5385.png)
![screen shot 2015-05-06 at 5 18 22 pm](https://cloud.githubusercontent.com/assets/11497391/7490548/ffaf4ed2-f413-11e4-9e8f-6139dd580bcb.png)

Kindly assist with this problem.

**Comment by kaerumy** [comment]
I think this is because it was just a Page, and at this  time page doesn't have any alternative views. It's under Project folder now which has display options so this should be "fixed".
